// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCp3_vo2ECrdlapcPiStezYXx5WaPlKM4',
    appId: '1:672314956972:web:f219fb029d5814f6b29309',
    messagingSenderId: '672314956972',
    projectId: 'mobile-app-casa0015',
    authDomain: 'mobile-app-casa0015.firebaseapp.com',
    storageBucket: 'mobile-app-casa0015.firebasestorage.app',
    measurementId: 'G-XY5R9QWB11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGDK6mKdVv6wkJNhT9eZk4dz6sikZxMhM',
    appId: '1:672314956972:android:13db3971776a5db1b29309',
    messagingSenderId: '672314956972',
    projectId: 'mobile-app-casa0015',
    storageBucket: 'mobile-app-casa0015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYc4rP4M_r52kxmjW2sg_yXUORnmGLik',
    appId: '1:672314956972:ios:ed305b8592fe33b6b29309',
    messagingSenderId: '672314956972',
    projectId: 'mobile-app-casa0015',
    storageBucket: 'mobile-app-casa0015.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYc4rP4M_r52kxmjW2sg_yXUORnmGLik',
    appId: '1:672314956972:ios:ed305b8592fe33b6b29309',
    messagingSenderId: '672314956972',
    projectId: 'mobile-app-casa0015',
    storageBucket: 'mobile-app-casa0015.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCp3_vo2ECrdlapcPiStezYXx5WaPlKM4',
    appId: '1:672314956972:web:f9251b50cfe4b696b29309',
    messagingSenderId: '672314956972',
    projectId: 'mobile-app-casa0015',
    authDomain: 'mobile-app-casa0015.firebaseapp.com',
    storageBucket: 'mobile-app-casa0015.firebasestorage.app',
    measurementId: 'G-0X5DR85GB7',
  );

}